name: RSI Bot Runner

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalışır
  workflow_dispatch:      # Manuel çalıştırma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/checkout@v2 # Not: Burayı v2 yapalım daha stabil

      - name: Install dependencies
        run: |
          pip install pandas ccxt pyTelegramBotAPI

      - name: Run bot
        run: python bot.py
